#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# clear message queue

_clrmsgq_usage="Clear Message Queues

clrmsgq -g|--msgq 'msgq'

- Clear Message Queues for an user"

_clrmsgq_options="JA_MSGQ rp@
JA_LINES rp@
JA_USR"

_clrmsgq() {
	local msgq

	msgq="${JA_USR_DIR}${JA_MSGQ}.msgq"
	if ! _test_rw "${msgq}"; then
		_usr_notify "Error: Not authorized to clear message queue '${JA_MSGQ}' for user '${JA_USR}'."
		return 1
	fi
	if [ "${JA_LINES}" -eq 0 ]; then
		truncate -s 0 "${msgq}"
	else
		cp "${msgq}" "${msgq}~"
		tail --lines="${JA_LINES}" "${msgq}~" > "${msgq}"
		rm -f "${msgq}~"
	fi
	_usr_notify "Clearing message queue '${JA_MSGQ}' for user '${JA_USR}'."
}
