#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# Delete a Job

_dltjob_usage="Delete Job

dltjob -j|--job 'JOBNAME'

delete a job and their related executions data"

_dltjob_options="JA_JOB pr@
JA_USR pr@"

_dltjob() {
	local fd1

	if ! _test_rw "${JA_JOB_DIR}"; then
		_usr_notify "Error: Not authorized to delete job '${JA_JOB}.${JA_USR}'."
		return 1
	fi

	( if ! flock --exclusive --timeout 1 ${fd1}; then
		_usr_notify "Error: job '${JA_JOB}.${JA_USR}' is locked."
		return 1
	fi

	rm -rf "${JA_JOB_DIR}"
	[ ! -s "${JA_USR_DIR}${JA_USR_SCDJOBS}" ] || \
		printf '%s\n' "g/^${JA_JOB}$/d" 'w' | \
		ed -s "${JA_USR_DIR}${JA_USR_SCDJOBS}" || :
	_usr_notify "Removing job '${JA_JOB}.${JA_USR}'."

	) {fd1}< "$(_flock_lckfile "${JA_JOB_DIR}")"
} # dltjob
