#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# displays the cmd scripts for a job

_dspjobcmd_usage="Display Job Cmd Script

dspjobcmd -j|--job 'JOBNAME' [ -e|--pid 'JOBPID' ]

- display cmd scripts of a job"

_dspjobcmd_options="JA_JOB pr@
JA_USR@
JA_PID"

_dspjobcmd() {
	local cmd

	if ! test -r "${JA_JOB_DIR}"; then
		_usr_notify "Error: Not authorized to manage job '${JA_JOB}.${JA_USR}'."
		return 1
	fi

	[ -z "${JA_PID}" ] || \
		JA_PID="$(_job_exist_exec)" || \
		return 1

	cmd="${JA_JOB_DIR}job${JA_PID:+"-${JA_PID}"}.cmd"
	if [ -s "${cmd}" ]; then
		_usr_notify "Displaying cmd script for job '${JA_JOB}.${JA_USR}${JA_PID:+".${JA_PID}"}'."
		_dspfiles "${cmd}"
	else
		_usr_notify "Can't find a cmd script for job '${JA_JOB}.${JA_USR}${JA_PID:+".${JA_PID}"}'."
		return 1
	fi
} # dspjobcmd
