#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# displays the log files for a job

_dspjoblog_usage="Display Job Log

dspjoblog -j|--job 'JOBNAME' [ -e|--pid 'JOBPID' ]

- display log files of a job"

_dspjoblog_options="JA_JOB pr@
JA_USR@
JA_PID"

_dspjoblog() {
	local files

	if ! test -r "${JA_JOB_DIR}"; then
		_usr_notify "Error: Not authorized to manage job '${JA_JOB}.${JA_USR}'."
		return 1
	fi

	[ -n "${JA_PID}" ] || \
		JA_PID="$(_job_exist_exec)" || \
			return 1

	if files="$(_expand_glob "${JA_JOB_DIR}job-${JA_PID}-*.splf")"; then
		_usr_notify "Displaying logs for job '${JA_JOB}.${JA_USR}.${JA_PID}'."
		local farray=() f
		while read f; do
			farray+=("$f")
		done <<< "${files}"
		_dspfiles "${farray[@]}"
	else
		_usr_notify "Not found any logs for job '${JA_JOB}.${JA_USR}.${JA_PID}'."
		return 1
	fi
	:
} # dspjoblog
