#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# display message file

_dspmsg_usage="Display Message Queues

dspmsg -g|--msgq 'msgq'

- display job messages for an user"

_dspmsg_options="JA_MSGQ pr@
JA_USR"

_dspmsg() {
	local msgq msgqs

	msgq="${JA_USR_DIR}${JA_MSGQ}.msgq"
	if [ -r "${msgq}" ]; then
		_usr_notify "Displaying message queue '${JA_MSGQ}' for user '${JA_USR}'."
		_dspfiles "${msgq}"
		return 0
	else
		if test -f "${msgq}"; then
			_usr_notify "Error: Message queue '${JA_MSGQ}' not exist for user '${JA_USR}'."
		else
			_usr_notify "Error: Not authorized to read message queue '${JA_MSGQ}' of user '${JA_USR}'."
		fi
		return 1
	fi
} # dspmsg
