#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# dspsplfa

_dspsplfa_options="JA_SPLF pr@
JA_JOB pr@
JA_USR@
JA_PID"

_dspsplfa() {
	local fd1

	if ! test -r "${JA_SPLF_ATTRS}"; then
		_usr_notify "Error: Not authorized to read spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'."
		return 1
	fi

	( if ! flock --shared --nonblock ${fd1}; then
		_usr_notify "Error: job '${JA_JOB}.${JA_USR}' is locked."
		return 1
	fi
	_usr_notify "Displaying spool file attributes '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'."
	( printf '%s\n\n' "Spool File Attributes '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'"
		_printvars "${JA_SPLF_ATTRS}"
	) 2>&1 | pager
	) {fd1}< "$(_flock_lckfile "${JA_JOB_DIR}")"
} # dspsplfa
