#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# dspwtr

_dspwtr_options="JA_WTR rp"

_dspwtr() {
	local wtr sts hld prt fd1

	wtr="${JA_SPOOL}${JA_WTR}.wtr"
	if ! test -r "${wtr}"; then
		_usr_notify "Error: Not authorized to manage writer '${JA_WTR}'."
	fi

	( if ! flock --shared --timeout 1 ${fd1}; then
		_usr_notify "Error: writer '${JA_WTR}' is locked."
		return 1
	fi
	hld="$(_read_option "JA_HLD" "${JA_SPOOL}${JA_WTR}.wtr.attrs")" || :
	if sts="$(_read_option "JA_WTR_STS" "${wtr}")"; then
		_usr_notify "Writer '${JA_WTR}' is not active, status '${sts}${hld:+"/${hld}"}'."
	else
		outqs="$(_read_option "JA_WTR_OUTQS" "${wtr}")"
		prt="$(_read_option "JA_PRT" "${wtr}")"
		_usr_notify "Writer '${JA_WTR}' is ${hld:-"ACT"}${hld:+"ACT/${hld}"}, \
sending to printer '${prt}' from output queues '${outqs}'."
	fi
	) {fd1}< "$(_flock_lckfile "${wtr}")"
} # dspwtr
