#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# endsplfprt

_endsplfprt_options="JA_SPLF pr@
JA_JOB pr@
JA_USR@
JA_PID"

_endsplfprt() {
	local sts request fd1

	if ! _test_rw "${JA_SPLF_ATTRS}"; then
		_usr_notify "Error: Not authorized to end printing of spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'."
		return 1
	fi

	( if ! flock --shared --timeout 1 ${fd1}; then
		_usr_notify "Error: job '${JA_JOB}.${JA_USR}' is locked."
		return 1
	fi
	sts="$(_read_option "JA_SPLF_STS" "${JA_SPLF_ATTRS}")" || sts="RDY"
	if [ "${sts}" != "WTR" ]; then
		_usr_notify "Error: spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}' is not printing, current status '${sts}'."
		return 1
	fi

	if request="$(_read_option "JA_REQUEST" "${JA_SPLF_ATTRS}")" && \
	cancel -U "${JA_USR}" "${request}" && \
	_set_option "${JA_SPLF_ATTRS}" "JA_CAUSE" "CAN" && \
	_set_option "${JA_SPLF_ATTRS}" "JA_WTR_ACTION" "SAV" && \
	_pipe_wtr_write "_jobadmin:${JA_SPLF}.${JA_JOB}.${JA_USR}.${JA_PID}"; then
		_usr_notify "Cancelling print request '${request}' for \
spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'."
	fi
	) {fd1}< "$(_flock_lckfile "${JA_JOB_DIR}")"
} # endsplfprt
