#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# rlssplf

_rlssplf_options="JA_SPLF pr@
JA_JOB pr@
JA_USR@
JA_PID"

_rlssplf() {
	local sts fd1

	if ! _test_rw "${JA_SPLF_ATTRS}"; then
		_usr_notify "Error: Not authorized to manage spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'."
		return 1
	fi

	( if ! flock --shared --timeout 1 ${fd1}; then
		_usr_notify "Error: job '${JA_JOB}.${JA_USR}' is locked."
		return 1
	fi
	sts="$(_read_option "JA_SPLF_STS" "${JA_SPLF_ATTRS}")" || sts="RDY"
	if [ "${sts}" != "RDY" ] && \
	[ "${sts}" != "SAV" ]; then
		_usr_notify "Error: spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}' is not held, current status '${sts}'."
		return 1
	fi
	if ! _read_option "JA_HLD" "${JA_SPLF_ATTRS}" > /dev/null && \
	[ "${sts}" != "SAV" ]; then
		_usr_notify "Warning: spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}' is not held."
		return 0
	fi

	if _set_option "${JA_SPLF_ATTRS}" "JA_SPLF_STS" "" && \
	_set_option "${JA_SPLF_ATTRS}" "JA_DATERLS" "$(date +%s)" && \
	_set_option "${JA_SPLF_ATTRS}" "JA_HLD" "" && \
	_pipe_write "_jobadmin"; then
		grep -qsxe "${JA_SPLF}" "${JA_USR_DIR}${JA_USR_SCDSPLFS}" || \
			printf '%s\n' "{JA_JOB} ${JA_SPLF}" >> "${JA_USR_DIR}${JA_USR_SCDSPLFS}"
		_usr_notify "Releasing $(test "${sts}" != "SAV" || \
printf 'saved ')spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'."
	else
		_usr_notify "Error: Not authorized to manage spool file '${JA_SPLF} ${JA_JOB}.${JA_USR}.${JA_PID}'."
		return 1
	fi
	) {fd1}< "$(_flock_lckfile "${JA_JOB_DIR}")"
} # rlssplf
