#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# rlswtr
_rlswtr_usage="End Writer

rlswtr -w|--wtr 'WRITER'

Release a writer."

_rlswtr_options="JA_WTR rp"

_rlswtr() {
	local sts hld

	if ! hld="$(_read_option "JA_HLD" "${JA_SPOOL}${JA_WTR}.wtr.attrs")"; then
		sts="$(_read_option "JA_WTR_STS" "${wtr}")" || :
		_usr_notify "Warning: $(test -n "${sts}" && printf '%s' "Stopped" || printf '%s' "Active") writer '${JA_WTR}' is not held."
		return 0
	fi

	if _set_option "${JA_SPOOL}${JA_WTR}.wtr.attrs" "JA_HLD" "" && \
	_pipe_write "_jobadmin"; then
		_usr_notify "Releasing writer '${JA_WTR}'."
	else
		_usr_notify "Error: Not authorized to release writer '${JA_WTR}'."
		return 1
	fi
} # rlswtr
