#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

#

_rnmjob_options="JA_JOB pr@
JA_NEWJOB pr@
JA_USR"

_rnmjob() {
	local fd1 attrs sts

	attrs="${JA_JOB_DIR}job.attrs"

	if ! _test_rw "${JA_JOB_DIR}job.cmd" || \
	! _test_rw "${attrs}"; then
		_usr_notify "Error: Not authorized to change job '${JA_JOB}.${JA_USR}'."
		return 1
	fi

	if [ -e "${JA_USR_DIR}${JA_NEWJOB}.job" ]; then
		_usr_notify "Error: Already existent job '${JA_NEWJOB}.${JA_USR}'."
		return 1
	fi

	( if ! flock --exclusive --timeout 1 ${fd1}; then
		_usr_notify "Error: job '${JA_JOB}.${JA_USR}' is locked."
		return 1
	fi
	[ ! -s "${JA_USR_DIR}${JA_USR_SCDJOBS}" ] || \
		printf '%s\n' "g/^${JA_JOB}$/d" 'w' | \
		ed -s "${JA_USR_DIR}${JA_USR_SCDJOBS}" || :
	sts="$(_read_option "JA_JOB_STS" "${attrs}")" || \
		grep -qsxe "${JA_NEWJOB}" "${JA_USR_DIR}${JA_USR_SCDJOBS}" || \
		printf '%s\n' "${JA_NEWJOB}" >> "${JA_USR_DIR}${JA_USR_SCDJOBS}"
	mv "${JA_JOB_DIR}" "${JA_USR_DIR}${JA_NEWJOB}.job"
	_usr_notify "Renaming job '${JA_JOB}.${JA_USR}' to '${JA_NEWJOB}'."
	_pipe_write "_jobadmin" || :
	) {fd1}< "$(_flock_lckfile "${JA_JOB_DIR}")"
} # rnmjob
