#!/bin/bash

#  Jobs management application for the Linux OS
#  $Revision: 1.66 $
#
#  Copyright (C) 2008-2017 Jordi Pujol <jordipujolp AT gmail DOT com>
#
#  This file is part of the LneT Jobadmin package,
#   http://livenet.ddns.net .
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 1, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Please report bugs to <jordipujolp AT gmail DOT com>.
#
#
#************************************************************************

# starts a subsystem

_strsbs_usage="Start Subsystem

strsbs -b|--sbsd 'SBSD'

- starts a subsystem"

_strsbs_options="JA_SBSD rp"

_strsbs() {
	local hld

	if ! _test_rw "${JA_SPOOL}${JA_SBSD}.sbsd"; then
		_usr_notify "Error: Not authorized to manage subsystem '${JA_SBSD}'."
		return 1
	fi

	hld="$(_read_option "JA_HLD" "${JA_SPOOL}${JA_SBSD}.sbsd.attrs")" || :
	if ! dummy="$(_read_option "JA_SBSD_STS" "${JA_SPOOL}${JA_SBSD}.sbsd")"; then
		_usr_notify "Warning: ${hld:+"Held "}subsystem '${JA_SBSD}' is already active."
		return 0
	fi

	if _pipe_daemon_write "_strsbs:${JA_SBSD}:${JA_USRACT} ${SUDO_USER:-}"; then
		_usr_notify "Starting ${hld:+"a held "}subsystem '${JA_SBSD}'."
	else
		_usr_notify "Error: Not authorized to manage subsystem '${JA_SBSD}'."
		return 1
	fi
} # strsbs
